add test project

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -11,18 +11,18 @@ jobs:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Setup Java
-        uses: actions/setup-java@v2
-        with:
-          distribution: "zulu"
-          java-version: "12.x"
-          cache: 'gradle'
-      - name: Setup Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: "3.7.10"
-          channel: 'stable'
-          cache: true
+#      - name: Setup Java
+#        uses: actions/setup-java@v2
+#        with:
+#          distribution: "zulu"
+#          java-version: "12.x"
+#          cache: 'gradle'
+#      - name: Setup Flutter
+#        uses: subosito/flutter-action@v2
+#        with:
+#          flutter-version: "3.7.10"
+#          channel: 'stable'
+#          cache: true
 #      - name: 🔐 Retrieve base64 keystore and decode it to a file
 #        env:
 #          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
@@ -48,29 +48,29 @@ jobs:
 #          echo keyAlias=\${{ secrets.KEYSTORE_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
       - name: 📝🔐 Create keystore.properties file
         run: |
-          echo storePassword=${{ secrets.KEYSTORE_PASSWORD }} >> android/key.properties
-          echo keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }} >> android/key.properties
-          echo keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }} >> android/key.properties
-          echo storeFile=keystore.jks >> android/key.properties
+          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
+          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> android/key.properties
+          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> android/key.properties
+          echo "storeFile=keystore.jks" >> android/key.properties
 
-      - name: 🔐 Retrieve base64 keystore and decode it to a file
-        run: |
-          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
-          chmod +x android/app/keystore.jks
-      - name: Verify JKS File
-        run: |
-          if [ -f "android/app/keystore.jks" ]; then
-            echo "JKS file created successfully!"
-          else
-            echo "Failed to create JKS file!"
-            exit 1
-          fi
-
-      - name: Build Android App Bundle
-        run: flutter build appbundle
-
-      - name: Save Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: app-bundle
-          path: build/app/outputs/bundle/release/app-release.aab
+#      - name: 🔐 Retrieve base64 keystore and decode it to a file
+#        run: |
+#          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
+#          chmod +x android/app/keystore.jks
+#      - name: Verify JKS File
+#        run: |
+#          if [ -f "android/app/keystore.jks" ]; then
+#            echo "JKS file created successfully!"
+#          else
+#            echo "Failed to create JKS file!"
+#            exit 1
+#          fi
+#
+#      - name: Build Android App Bundle
+#        run: flutter build appbundle
+#
+#      - name: Save Artifact
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: app-bundle
+#          path: build/app/outputs/bundle/release/app-release.aab
